# Generated by Django 3.2 on 2021-12-29 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(blank=True, null=True)),
                ('t_coin', models.CharField(blank=True, max_length=4, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('token', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CoinBalance',
                'verbose_name_plural': 'CoinBalances',
                'db_table': 'coinbalance',
            },
        ),
        migrations.CreateModel(
            name='NFTBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_nft', models.CharField(blank=True, max_length=4, null=True)),
                ('token', models.FloatField(blank=True, default=0, null=True)),
                ('analyze_assets', models.CharField(blank=True, max_length=10, null=True)),
                ('identify_assets', models.CharField(blank=True, max_length=20, null=True)),
                ('land_item_axie', models.CharField(blank=True, max_length=15, null=True)),
                ('acarcity_class', models.CharField(blank=True, max_length=15, null=True)),
                ('market_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NFTBalance',
                'verbose_name_plural': 'NFTBalances',
                'db_table': 'nftbalance',
            },
        ),
        migrations.CreateModel(
            name='Txn',
            fields=[
                ('parent_txn_hash', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('block', models.IntegerField(blank=True, null=True)),
                ('from_txn', models.CharField(blank=True, max_length=40, null=True)),
                ('to_txn', models.CharField(blank=True, max_length=40, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('t_txn', models.CharField(blank=True, max_length=4, null=True)),
                ('txn_fees', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('coin_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.coinbalance')),
                ('nft_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.nftbalance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Txn',
                'verbose_name_plural': 'Txns',
                'db_table': 'txns',
            },
        ),
        migrations.CreateModel(
            name='RoningPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roning', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoningGaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roning', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/avatars/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('wallet', models.CharField(blank=True, max_length=64, null=True)),
                ('t_wallet', models.CharField(blank=True, max_length=15, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('front_DNI', models.ImageField(blank=True, null=True, upload_to='images/front_dni/')),
                ('back_DNI', models.ImageField(blank=True, null=True, upload_to='images/back_dni/')),
                ('tipo_user', models.CharField(choices=[('GEN', 'General'), ('GAM', 'Gaming'), ('SPO', 'Sponsor'), ('INT', 'Internal')], default='', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'person',
            },
        ),
    ]
